config/routes.rb
Rails.application.routes.draw do
  resources :matches
  resources :players
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'homepage#home'
  get '/new' => 'players#new'
  get '/standings' => 'players#standings'
  # get '/matches' => 'players#standings'
  get '/login' => 'players#login_page'
  post '/login' => 'players#login'
  get '/logout' => 'players#logout'
  get '/challenge' => 'players#challenge'
  post '/challenge' => 'players#create_challenge'
  get '/rules' => 'homepage#rules'
end

app/models/player.rb
class Player < ApplicationRecord
  has_secure_password
  belongs_to :league
  has_many :player_matches
  has_many :matches, through: :player_matches
# has_and_belongs_to_many :matches
  validates :user_name, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  # validates :password, presence: true
  
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]
  before_action :current_player
  before_action :admin_access, only: [:index, :edit, :update, :destroy]
  before_action :current_leauge, only: [:standings]
  before_action :standings_array, only: [:standings, :create]
  before_action :not_a_user, only: [:standings]
  #GET /login
  def login_page
  end
  #GET /players
  def index
    @players = Player.all
  end
  #post /login
  def login
     @player = Player.find_by(user_name: params[:user_name])
      # If the player exists AND the password entered is correct.

      if @player && @player.authenticate(params[:password])
         session[:player_user_name] = @player.user_name
        redirect_to @player, alert: "Welcome, #{@player.first_name}"
        current_player
      else
          # If user's login doesn't work, send them back to the login form.
          # flash[:notice] =
      redirect_to login_path, alert: "unsucessful login"
      end
  end
  def logout
  reset_session
  redirect_to '/login', alert: "You are now logged out"
  end
  def standings
    update_standings
    @players = []
    Player.all.each do |player|
      if player.league_id == @current_player.league_id && player.user_name != "admin"
      @players << player
      end
    end
    @players = @players.sort { |a,b|
      a.standings_position <=> b.standings_position
    }
  end

  # GET /players/1
  # GET /players/1.json
  def show

  end

  # GET /players/new
  def new
    @league_names = []
    @player = Player.new
     League.all.each do |league|
    @league_names << league.league_name
  end
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    standings_array
    @player = Player.new(player_params)
    @player.wins = 0
    @player.losses = 0
    @player.pf = 0
    @player.pa = 0
    @player.win_percentage = 0
    session[:player_user_name] = @player.user_name
  #   if @player.user_name == "admin"
  #   @player.standings_position = 1200
  # else
    @player.standings_position = @standings_array.max + 1
  # end
    current_player
    respond_to do |format|
      if @player.save
        session[:player_user_name] = @player.user_name
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    Player.all.each do |player|
      if player.standings_position > @player.standings_position
      player.standings_position -= 1
      player.save
    end
  end

    @player.destroy

    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  #GET /challenge
  # def challenge
  # end
  #POST /challenge
  # def create_challenge
  #   if Player.find_by(user_name: params[:user_name]).nil?
  #     redirect_to '/challenge', alert: "That Player doesn't exists, Please enter players username"
  # elsif @current_player.standings_position  < Player.find_by(user_name: params[:user_name]).standings_position
  #     redirect_to '/challenge', alert: "Sorry your rank is higher than #{Player.find_by(user_name: params[:user_name]).user_name}'s rank"
  #   else
  #     #alert other player that they have been challenged!
  #     redirect_to '/matches/new', alert: "Player has been challenged"
  #
  #   end
  # end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:first_name, :last_name, :user_name, :password, :password_confirmation, :league_id)
    end
    def update_standings
      Player.all.each do |player|
        if player.losses == 0 && player.wins == 0
          player.update(win_percentage: 0)
        elsif player.losses == 0
          player.update(win_percentage: 100)
        else
          d = player.wins + player.losses.to_f
        player.update win_percentage: (player.wins / d * 100).round(2)
        end
      end
    end
    def admin_access
      return redirect_to '/' if @current_player.nil? || @current_player.user_name != "admin"
    end
    def standings_array
      @standings_array = [0]
      Player.all.each do |player|
        next if player.user_name == "admin"
        next if player.standings_position == nil
        @standings_array << player.standings_position
      end
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(player) do |f| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :user_name %>
    <%= f.text_field :user_name %>

  <div class="field">
<%= f.label :password %>
<%= f.password_field :password %>
</div>
<div class="field">
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
</div>
<!-- # <% if @current_player && @current_player.user_name == "admin" %>
# <%= f.label :standings_position %>
# <%= f.text_field :standings_position %>
# <% end %> -->
<div class="field">
<%= f.collection_select(:league_id, League.all, :id, :league_name, {:prompt => 'Select a League', :selected => @player.league_id})%>
</div>
  <div class="actions">
    <%= f.submit "Create Player" %>
  </div>
<% end %>

app/views/players/challenge.html.erb
<h1>Challenge</h1>
<!-- <p> Note you can only challenge players with a rank that is higher than yours</p> -->

<h1><%= alert %></h1>
<%= form_tag '/challenge' do %>

  <div class="field">
    <%= label_tag :user_name %>
    <%= text_field_tag :user_name %>
  </div>

  <%= submit_tag "Challenge" %>

<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

 <h1>Players</h1>

 <table class = "table">
   <thead>
    <tr>
       <th>Name</th>
       <th>user_name</th>
       <th>Wins</th>
       <th>Losses</th>
       <th>Points For</th>
       <th>Points Against</th>
       <th>League Name</th>
       <th>Ladder Position</th>
       <th colspan="3"></th>
     </tr>
   </thead>

   <tbody>
     <% @players.each do |player| %>
       <tr>
         <td><%= player.first_name + " " + player.last_name %></td>
         <td><%= player.user_name %></td>
         <td><%= player.wins %></td>
         <td><%= player.losses %></td>
         <td><%= player.pf %></td>
         <td><%= player.pa %></td>
         <td><%= player.league.league_name %></td>
         <td><%= player.standings_position %></td>
         <td><%= link_to 'Show', player %></td>
         <td><%= link_to 'Edit', edit_player_path(player) %></td>
         <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
       </tr>
     <% end %>
   </tbody>
 </table>

 <br>

 <%= link_to 'New Player', new_player_path %>

app/views/players/login_page.html.erb
<header>
  <ul class="nav nav-tabs nav-justified">
    <% if session[:player_user_name].nil? %>
    <!-- <li><%= link_to "login", '/login' %></li> -->
    <% else %>
      <li><%= link_to "logout", '/logout' %></li>
      <% end %>
    <li><%= link_to "Home", '/' %></li>
    <li><%= link_to 'New Player', '/new' %></li>
  </ul>
</header>
<h1><%= alert %></h1>
<h1>Login</h1>

<%= form_tag '/login' do %>

  <div class="field">
    <%= label_tag :user_name %>
    <%= text_field_tag :user_name %>
  </div>

  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
  </div>
  <%= submit_tag "Login" %>

<% end %>

app/views/players/new.html.erb
<header>
  <ul class="nav nav-tabs nav-justified">
    <!-- <li><%= link_to "login", '/login' %></li> -->
    <li><%= link_to "Home", '/' %></li>
    <li><%= link_to "Login", '/login' %></li>
    <!-- <li><%= link_to 'New Player', '/new' %></li>
    <li><%= link_to "Standings", '/standings' %></li>
    <li><%= link_to "Submit Score", '/matches/new' %></li> -->

  </ul>
</header>
<div class="field">

</div>
<div class="create_player">
  <div class= "player_header">
    <h1>Let's create a player</h1>
  </div>
  <div class="form">
    <%= render 'form', player: @player %>
  </div>
</div>

app/views/players/show.html.erb
<header>
  <ul class="nav nav-tabs nav-justified">
    <% if session[:player_user_name].nil? %>
    <li><%= link_to "login", '/login' %></li>
    <% else %>
      <li><%= link_to "logout", '/logout' %></li>
      <% end %>
    <li><%= link_to "Home", '/' %></li>
    <li><%= link_to "Standings", '/standings' %></li>
    <li><%= link_to "Submit Score", '/matches/new' %></li>
  </ul>
</header>
<div class="Welcome_message"><h1><%= alert %></h1></div>
<div class="player_bio">
  <div class = "player_head">
    <h1>Player Bio Page</h1>
    <p id="notice"><%= notice %></p>
  </div>

  <div class="player_text">
    <p>
      <strong>Name:</strong>
      <%=  @player.first_name.capitalize + " " + @player.last_name.capitalize %>
    </p>

    <p>
      <strong>Username:</strong>
      <%= @player.user_name %>
    </p>

    <p>
      <strong>Wins:</strong>
      <%= @player.wins %>
    </p>

    <p>
      <strong>Losses:</strong>
      <%= @player.losses %>
    </p>

    <p>
      <strong>Points For:</strong>
      <%= @player.pf %>
    </p>

    <p>
      <strong>Points Against:</strong>
      <%= @player.pa %>
    </p>
    <p>
      <strong>League:</strong>
      <%= @player.league.league_name %>
    </p>
  </div>
  <!-- <%= link_to 'Edit', edit_player_path(@player) %> | -->
  <button class= "button">
  <%= link_to "Standings", '/standings', :method => :get %>
  </button>
  </div>
</div>

app/views/players/standings.html.erb
<div class="top_bar">
<header>
  <ul class="nav nav-tabs nav-justified">
    <% if session[:player_user_name].nil? %>
    <li><%= link_to "login", '/login' %></li>
    <% else %>
      <li><%= link_to "logout", '/logout' %></li>
      <% end %>
    <li><%= link_to "Home", '/' %></li>
    <li><%= link_to "Submit Score", '/matches/new' %></li>
  </ul>
</header>
</div>
<h3><%= notice %></h3>
<div class="standings">
  <h1>Standings</h1>
</div>


<table class="table">
  <thead>
    <tr>
      <th>Rank</th>
      <th>Name</th>
      <th>Wins</th>
      <th>Losses</th>
      <th>Win Percentage</th>
      <!-- <th>Points For</th>
      <th>Points Against</th> -->
      <th>League</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% p @players %>
    <% @players.each_with_index do |player| %>
      <tr>
        <td><%= player.standings_position %></td>
        <td><%= link_to player.first_name + " " + player.last_name, player %></td>
        <td><%= player.wins %></td>
        <td><%= player.losses %></td>
        <td><%= player.win_percentage%> %</td>
        <!-- <td><%= player.pf %></td>
        <td><%= player.pa %></td> -->
        <td><%= player.league.league_name %></td>
        <!-- <td type="button" class="button"><%= link_to 'Show Player', player %></td> -->
        <!-- <td><%= link_to 'Edit', edit_player_path(player) %></td> -->
        <!-- <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>